### ISSUE TITLE
TypeError: simple_test_bboxes() missing 1 requiresd positional argument `proposals`

### ISSUE THREAD

**Issue by dragen1860** [Viredery/tf-eager-fasterrcnn#1]
![image](https://user-images.githubusercontent.com/4252555/52926631-b19ef980-338a-11e9-90c0-4fbbc1501c88.png)

Dear author:
  thank you for your eager mode faster rcnn. However, when i try to run your code, an error occcured. please help me how to solve this bugs. THank you.

**Comment by Viredery** [comment]
Hey dragen1860. This is my fault. Thank you for finding it!

`model.load_weights('weights/faster_rcnn.h5', by_name=True)
proposals = model.simple_test_rpn(img, img_meta)
res = model.simple_test_bboxes(img, img_meta, proposals)`
