### ISSUE TITLE
Problem in train_model.ipynb

### ISSUE THREAD

**Issue by AndrewNest** [Viredery/tf-eager-fasterrcnn#10]
When I excute the "train model" part,it comes out a InvalidArgumentError:indices[0] = [0, -1] does not index into shape [256,81,4] [Op:TensorScatterUpdate]. 
check on the debug list: error is in \detection\core\bbox\bbox_target.py in _build_single_target.
delta_targets = tf.tensor_scatter_nd_update(tile_delta_targets, ids, delta_targets)

the shape of **ids** is not match with **tile_delta_targets**. what is ids、tile_delta_targets？how could I fix this problem?  plead for your suggestion.

details is in the screenshot:
![1](https://user-images.githubusercontent.com/46395243/82139922-4fb79300-985e-11ea-9e70-5b466db611e8.png)
![2](https://user-images.githubusercontent.com/46395243/82139928-56dea100-985e-11ea-89f7-0bb856433495.png)
![3](https://user-images.githubusercontent.com/46395243/82139932-5c3beb80-985e-11ea-82d1-c87eec2b2a22.png)

**Comment by Viredery** [comment]
The easiest way to fix this problem is modify [the line 157](https://github.com/Viredery/tf-eager-fasterrcnn/blob/ac395e23ae93a19eb18cb0a9145c19f0491fb278/detection/core/bbox/bbox_target.py#L157) to
`labels = tf.pad(labels, [(0, P)], constant_values=0) # [num_rois]`


I haven't met this problem. It's weird.

**Comment by AndrewNest** [comment]
Thanks a lot. This method really works

**Comment by Viredery** [comment]
I've fixed the weight initialization method by removing he_normal. I think it could solve your problem without modifying [the line 157](https://github.com/Viredery/tf-eager-fasterrcnn/blob/ac395e23ae93a19eb18cb0a9145c19f0491fb278/detection/core/bbox/bbox_target.py#L157). 

I close this issue and you can open another issue if this problem still exists.
