### ISSUE TITLE
InvalidArgumentError: indices[204] = [204, -1] does not index into shape [256,81,4] [Op:TensorScatterUpdate]

### ISSUE THREAD

**Issue by arunraja-hub** [Viredery/tf-eager-fasterrcnn#15]
I tried running train_model.ipynb. My tf version is 2.0.0 and cuda version is 10.0.
But I am still getting the following error:
![image](https://user-images.githubusercontent.com/43485111/87666941-189d2980-c79c-11ea-85d9-8c07d83aee16.png)
Could you help me rectify this?

**Comment by Viredery** [comment]
Please follow this comment and it maybe help for you
https://github.com/Viredery/tf-eager-fasterrcnn/issues/10#issuecomment-629824408
