### ISSUE TITLE
different padded size on training and test

### ISSUE THREAD

**Issue by dragen1860** [Viredery/tf-eager-fasterrcnn#2]
Dear author:
  I noticed that when I train, your padded image size is to [1216, 1216], however, when i test, your padded image size is [1024, 1024]. Am i wrong or anything i misunderstood?
 by the way, what's the meaning of the parameters: `scale` in: 
```python
class CocoDataSet(object):
    def __init__(self, dataset_dir, subset,
                 flip_ratio=0,
                 pad_mode='fixed',
                 mean=(0, 0, 0),
                 std=(1, 1, 1),
                 scale=(1024, 800),
                 debug=False):
```

Thank you.

**Comment by Viredery** [comment]
hey, 我在图像填充上的处理不是很实用，所以目前这个项目还不大适合直接来训练模型。下面我来介绍下我目前设置的图像预处理过程

当scale设置为(1024, 800)时【注：常见的设置是(800，1333)，我调小就是为了省显存】
训练阶段：
首先，将图片rescale到(1024, 800)，具体地，另图片短边为800，但长边不能超过1024；否则，长边最大为1024，短边则小于800
然后，再填充到(1024, 1024)

预测阶段：
第一步和训练阶段一样，首先，将图片rescale到(1024, 800)
然后，再把高和宽填充到64的倍数

我说目前项目不适合训练，是因为，在模型的RCNN部分，我没有把RoI batch size填充到固定大小（如512），因此每次喂给模型一张图片，生成了不同数量的RoI，GPU都会开辟出一块显存，导致显存不够用。

**Comment by dragen1860** [comment]
好像网上就只要你的是用eager mode实现的faster rcnn, 你可以保持更新，你的工作很重要！谢谢。

**Comment by dragen1860** [comment]
你可以做一个训练自己数据集的教程吗，顺便解决`我说目前项目不适合训练`的问题。

**Comment by Viredery** [comment]
我一开始实现的时候，就计划实现目前这种 生成未填充 RoI 的代码，不同的图片生成的RoI放在一个list里。因为我用mxnet、pytorch时，都是这种不固定形状的动态形式。但我不知道为什么，tensorflow在这种情况下会费显存，可能需要设置下tensorflow的参数就可以避免这个问题？
［研二下学期事情比较多，可能暑假前没有更新的时间，抱歉］

训练自己数据集，可以参考coco.py这一个文件，只需要实现__len__和__getitem__就好。然后在外面包装一个迭代器［data_generator.py］，传入tf.data部分就好

**Comment by dragen1860** [comment]
好的，谢谢耐心指导。
