### ISSUE TITLE
Cannot download weights from Baidu

### ISSUE THREAD

**Issue by MichelHalmes** [Viredery/tf-eager-fasterrcnn#5]
Good day,
Thank you for your great work :+1:

Since I do not have a Chinese phone number, I cannot download the pretrained net.
Would it be possible to upload the file via google drive, dropbox, or even just publishing it on github?

Much appreciated! :-)

**Comment by Viredery** [comment]
Hi @MichelHalmes 
I upload the pre-trained model to Google Drive.
https://drive.google.com/file/d/1yCF-BqqM2x3bqWlJmAyDM-HuhDcLzt0t/view?usp=sharing

Thank you for your support

**Comment by MichelHalmes** [comment]
Thank you very much !! :-) :+1:
