### ISSUE TITLE
what is img_metas?

### ISSUE THREAD

**Issue by QiuSYang** [Viredery/tf-eager-fasterrcnn#6]
what does the img_metas variable contain.

**Comment by Viredery** [comment]
[original_shape_H, original_shape_W, original_shape_C, scaled_shape_H, scaled_shape_W, scaled_shape_C, padded_shape_H, padded_shape_W, padded_shape_C, scale_ratio, is_flip]

**Comment by QiuSYang** [comment]
> Hi @QiuSYang,
> 
> the composition of the img_meta is
> [original_shape_H, original_shape_W, original_shape_C, scaled_shape_H, scaled_shape_W, scaled_shape_C, padded_shape_H, padded_shape_W, padded_shape_C, scale_ratio, is_flip].
> 
> for example,
> the shape of an original image is [500, 605, 3], then re-scaled to [800, 968, 3], finally padded to [800, 992, 3] (multiples of 32)

I would like to ask you another question.
![image](https://user-images.githubusercontent.com/37255500/80268535-7577cf00-86da-11ea-9884-00ad36d8ce57.png)
The proposals coordinate in the figure has been normalized, but what we actually need is the actual pixel coordinates at the end. Have I found any conversion back? I'm not very clear about it

**Comment by Viredery** [comment]
You can check this [reference code](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L53). Codes about conversion back from normalized coord is in [func get_bboxes](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L77) and codes about conversion back from scaled and flipped coord in [func _unmold_detections](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L80)

**Comment by QiuSYang** [comment]
> You can check this [inference code](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L53). Codes about conversion back from normalized coord is in [func get_bboxes](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L77) and codes about conversion back from scaled and flipped coord in [func _unmold_detections](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L80)

Thank you. I'll study it carefully and consult you when I have any questions.

**Comment by QiuSYang** [comment]
> > You can check this [inference code](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L53). Codes about conversion back from normalized coord is in [func get_bboxes](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L77) and codes about conversion back from scaled and flipped coord in [func _unmold_detections](https://github.com/Viredery/tf-eager-fasterrcnn/blob/89cc374d17931aef6212efb5a58b8d838198fdea/detection/models/detectors/test_mixins.py#L80)
> 
> Thank you. I'll study it carefully and consult you when I have any questions.

hello, @Viredery 
I found a problem in line 169 of file bbox_target.py, as follows:
`delta_weights = tf.where(labels > 0,
                                     tf.ones((self.num_rcnn_deltas,), dtype=tf.float32) / num_bfg,
                                     label_weights)`
The reference file anchor_target.py(the 166 line) similar location code should be as follows:
`delta_weights = tf.where(labels > 0,
                                     tf.ones((self.num_rcnn_deltas,), dtype=tf.float32) / num_bfg,
                                     delta_weights)`
I'm just changing the tf.where() parameter **label_weights** to **delta_weights**, and I don't know if that's right.

**Comment by Viredery** [comment]
It's my fault. It should be

`delta_weights = tf.where(labels > 0, tf.ones((self.num_rcnn_deltas,), dtype=tf.float32) / num_bfg, label_weights)`

Thank you!

**Comment by QiuSYang** [comment]
> It's my fault. It should be
> 
> `delta_weights = tf.where(labels > 0, tf.ones((self.num_rcnn_deltas,), dtype=tf.float32) / num_bfg, label_weights)`
> 
> Thank you!

so, The correct codes is 
`delta_weights = tf.where(labels > 0, tf.ones((self.num_rcnn_deltas,), dtype=tf.float32) / num_bfg, delta_weights)`.
It's not what you described. Is it?

**Comment by Viredery** [comment]
Yeah, I modify this expression. And the value of `delta_weights` is the same as before modification.
