### ISSUE TITLE
Problems in inspect_model.ipynb

### ISSUE THREAD

**Issue by kuailedagongzai** [Viredery/tf-eager-fasterrcnn#7]
I get my jupyter restart when i excute '  _ = model((batch_imgs, batch_metas), training=False)  ',after dataset loaded. If i don't excute this line  ,i got a error  in load weights procedure. The sreenshots of these problems are as belows.
![problem1](https://user-images.githubusercontent.com/53248239/79824190-35f26f80-83c8-11ea-937a-a17fbb0ccee7.png)
![problem2](https://user-images.githubusercontent.com/53248239/79824194-38ed6000-83c8-11ea-8050-b19320cf7cb9.png)

**Comment by Viredery** [comment]
Hi @kuailedagongzai 

This is how eager mode works in TensorFlow2.

If you don't run the network at first, this model wouldn't know the structure of network, causing this "a model with 0 layers" problem.

**Comment by kuailedagongzai** [comment]
Thanks for advices,but everytime i try to feed the data into the model,my jupyter will restart.How could i avoid this situation?By the way, I tried this scripts in vscode ,then my vscode restart. I stored the data in anothor directory , so i made a little modification to coco.py .Does this matter ?These are my modifications.
![modification1](https://user-images.githubusercontent.com/53248239/79833004-2fbabe00-83dd-11ea-82f2-7c2387eff678.png)
![modification2](https://user-images.githubusercontent.com/53248239/79833006-32b5ae80-83dd-11ea-8921-f41fefd01c69.png)

**Comment by Viredery** [comment]
Maybe you could check out your GPU memory? One reason to cause this crash is OOM.

You can try this scripts in Terminal and figure it out~

**Comment by kuailedagongzai** [comment]
Actually,the GPU in my notebook could not be used. Therefore , i use CPU only. There are 12G memory in my systerm.And when i run this script in the terminal ,it report a 'Segmentation fault'
![fault](https://user-images.githubusercontent.com/53248239/79843249-9abfc100-83ec-11ea-9d34-117c56f56a8b.png)

**Comment by Viredery** [comment]
It can't work in my CPU either.
Maybe it's a bug?

**Comment by Viredery** [comment]
I fix this bug in [this commit](https://github.com/Viredery/tf-eager-fasterrcnn/commit/7eb7d7975ef56ddca6c5b1aef87d8977ce9dacdf)

Now the weight initialization method is Xavier(default) instead of He
